apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rollout.yaml
  - service.yaml

images:
  - name: blog-react-app 
    newName: us-central1-docker.pkg.dev/fadhil-351012/react-blog-argo-test/blog-react-app
    newTag: gh-blog-placeholder  # This will be dynamically updated by Argo CD Image Updater
