apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blog-react-app
  argocd-image-updater.argoproj.io/image-list: blog-react-app-image=us-central1-docker.pkg.dev/fadhil-351012/react-blog-argo-test/blog-react-app
  argocd-image-updater.argoproj.io/blog-react-app-image.update-strategy: digest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog-react-app 
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 30s}
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100
  template:
    metadata:
      labels:
        app: blog-react-app
    spec:
      containers:
        - name: blog-react-app
          image: "us-central1-docker.pkg.dev/fadhil-351012/react-blog-argo-test/blog-react-app:{{ .newTag }}"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: gar-credentials